[uwsgi]
module = flaskr.index:app

protocol = http
http-socket = :5000

master = true
vacuum = true
die-on-term = true

workers = 1
gevent = 1000

gevent-early-monkey-patch = true
lazy-apps = true

enable-threads = false
single-interpreter = true